name: TNTFly
main: fr.ayzlow.tntfly.Main
version: 1.0.1
api-version: 1.13
description: Implement TNT-Fly on your server.
author: Ayzlow
commands: {}

permissions:
  tntfly.use:
    description: Allows a player to fly after being affected by TNT.
    default: true
